version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: sales of Greenweez, there is one row per products_id found in each orders_id
        columns:
          - name: products_id
            description: primary_key
            tests:
              - unique
              - not_null

      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: "orders_id || pdt_id"
            description: primary_key
            tests:
              - unique
              - not_null        
      
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary_key
            tests:
              - unique
              - not_null          

      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook

models:
  - name: int_campaigns
    description: group of all our ad campaign
    columns:
      - name: "date_date || campaign_key"
        description: primary_key
        tests:
          - unique
          - not_null
      - name: paid_source
        description: listing of whom we paid
        tests:
          - not_null  
      - name: campaign_name
        description: listing of names of campaigns
        tests:
          - not_null 
      - name: ads_cost
        description: listing of the price of the campaign
        tests:
          - not_null 
      - name: impression
        description: results of views
        tests:
          - not_null 
      - name: click
        description: listing of transformation
        tests:
          - not_null 

  - name: int_campaigns_day
    description: aggregation of the impact of our ads campaigns per day
    columns:
      - name: date_date
        tests:
          - unique
  - name: finance_campaigns_day
    description: aggregation of the ads margin per day
      

